spring.application.name=smokecast

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/fire_catalog}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:smokecast123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${SERVER_PORT:8081}