spring.application.name=ms1-fire-catalog
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3306/fire_catalog}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.hikari.connection-timeout=5000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.port=${SERVER_PORT:8081}
server.address=${HOST:127.0.0.1}
springdoc.api-docs.path=/openapi.json
springdoc.swagger-ui.path=/docs
springdoc.swagger-ui.url=${PUBLIC_OPENAPI_URL:openapi.json}
